import { TableField } from "./types";

// Исходные данные таблицы
export const initialData: TableField[][] = [
  [
    {
      id: 0,
      name: "date",
      value: "30 января 2024",
      type: "text",
      colSpan: 2,
      fontWeight: "bold",
      rowSpan: 1,
      align: "left",
    },
    {
      id: 1,
      name: "shift",
      value: "Смена 2",
      type: "text",
      colSpan: 1,
      fontWeight: "bold",
      rowSpan: 1,
      align: "left",
    },
    {
      id: 2,
      name: "master",
      value: "Иванов И. И.",
      type: "fio",
      colSpan: 6,
      fontWeight: "bold",
      rowSpan: 1,
      label: "Мастер:",
      align: "left",
    },
    {
      id: 3,
      name: "code",
      value: "РПТКМ-120",
      type: "text",
      colSpan: 2,
      fontWeight: "bold",
      rowSpan: 1,
      align: "left",
    },
  ],
  [
    {
      id: 4,
      name: "personnel",
      value: "Персонал",
      type: "text",
      colSpan: 2,
      fontWeight: "bold",
      rowSpan: 1,
      align: "left",
    },
    {
      id: 5,
      name: "personnelCount",
      value: "100500 человек",
      type: "text",
      colSpan: 6,
      fontWeight: "bold",
      rowSpan: 1,
      align: "center",
    },
    {
      id: 6,
      name: "comment",
      value: "Комментарий в 3-5 строчек, который тоже можно редактировать.",
      type: "text",
      colSpan: 3,
      rowSpan: 3,
      fontWeight: "500",
      align: "left",
      multiLine: true,
    },
  ],
  [
    {
      id: 7,
      name: "ktp",
      value: "КТП 2000 321",
      type: "text",
      colSpan: 2,
      rowSpan: 2,
      fontWeight: "bold",
      align: "left",
    },
    {
      id: 8,
      name: "status",
      value: "Работает",
      type: "text",
      colSpan: 3,
      fontWeight: "bold",
      rowSpan: 1,
      align: "left",
    },
    {
      id: 9,
      name: "count",
      value: "24",
      type: "number",
      colSpan: 1,
      fontWeight: "bold",
      rowSpan: 1,
      align: "center",
    },
    {
      id: 10,
      name: "spi",
      value: "SPI 3432",
      type: "text",
      colSpan: 2,
      fontWeight: "bold",
      rowSpan: 1,
      align: "left",
    },
  ],
  [
    {
      id: 11,
      name: "efficiency",
      value: "98.4",
      type: "percent",
      colSpan: 1,
      fontWeight: "bold",
      rowSpan: 1,
      align: "left",
    },
    {
      id: 12,
      name: "error",
      value: "Функционирует, но не бьет",
      type: "text",
      colSpan: 5,
      fontWeight: "bold",
      color: "red",
      rowSpan: 1,
      align: "left",
    },
  ],
];
